"""Email test results with failures/important checks in the body and a PDF of other passes."""

import os
import re
import smtplib
from email.message import EmailMessage
from pathlib import Path


DEFAULT_SUBJECT = "Surya Sangam Automation Execution Report"
DEFAULT_IMPORTANT_CATEGORIES = (
    "Homepage",
    "Contact",
    "Contact Validation",
    "Calculator",
)
DEFAULT_IMPORTANT_KEYWORDS = (
    "homepage",
    "contact",
    "calculator",
    "navigation",
    "service",
    "security",
)
_TEST_HEADER = re.compile(r"^TC\d+ - (.+)$")


class EmailReportConfigError(ValueError):
    """Raised when required email configuration is missing or invalid."""


def send_report_email(report_path):
    """Send a focused email summary and a PDF of the remaining passed tests.

    The report text is split into test-case blocks. Failed and skipped tests are
    always included in the email body. Passed tests are included in the body
    when their area or name is considered important. All other passed tests
    are included in a PDF attachment.

    Optional environment variables:
        SURYA_REPORT_IMPORTANT_CATEGORIES
            Comma-separated report areas to include in the email body.
        SURYA_REPORT_IMPORTANT_KEYWORDS
            Comma-separated case-insensitive words matched against test names.
    """
    report_path = Path(report_path)
    _validate_report(report_path)

    config = _load_email_config()
    message = _build_message(config, report_path)

    with smtplib.SMTP(config["host"], config["port"]) as smtp:
        if config["use_tls"]:
            smtp.starttls()
        smtp.login(config["username"], config["password"])
        recipients = config["to"] + config["cc"] + config["bcc"]
        smtp.send_message(message, to_addrs=recipients)


def is_email_configured():
    """Return True when the required email environment variables are present."""
    required_keys = (
        "SMTP_HOST",
        "SMTP_USER",
        "SMTP_PASSWORD",
        "SURYA_REPORT_EMAIL_TO",
    )
    return all(os.getenv(key) for key in required_keys)


def _load_email_config():
    missing_keys = [
        key
        for key in (
            "SMTP_HOST",
            "SMTP_USER",
            "SMTP_PASSWORD",
            "SURYA_REPORT_EMAIL_TO",
        )
        if not os.getenv(key)
    ]
    if missing_keys:
        raise EmailReportConfigError(
            "Missing email configuration: " + ", ".join(missing_keys)
        )

    try:
        port = int(os.getenv("SMTP_PORT", "587"))
    except ValueError as error:
        raise EmailReportConfigError("SMTP_PORT must be a number.") from error

    recipients = _parse_addresses(os.getenv("SURYA_REPORT_EMAIL_TO", ""))
    if not recipients:
        raise EmailReportConfigError("SURYA_REPORT_EMAIL_TO must include an address.")

    return {
        "host": os.getenv("SMTP_HOST"),
        "port": port,
        "username": os.getenv("SMTP_USER"),
        "password": os.getenv("SMTP_PASSWORD"),
        "sender": os.getenv("SMTP_FROM", os.getenv("SMTP_USER")),
        "to": recipients,
        "cc": _parse_addresses(os.getenv("SURYA_REPORT_EMAIL_CC", "")),
        "bcc": _parse_addresses(os.getenv("SURYA_REPORT_EMAIL_BCC", "")),
        "subject": os.getenv("SURYA_REPORT_EMAIL_SUBJECT", DEFAULT_SUBJECT),
        "use_tls": os.getenv("SMTP_USE_TLS", "true").lower() in ("1", "true", "yes"),
    }


def _build_message(config, report_path):
    results = _parse_test_blocks(report_path.read_text(encoding="utf-8"))
    body_results, passed_for_pdf = _split_results(results)

    message = EmailMessage()
    message["From"] = config["sender"]
    message["To"] = ", ".join(config["to"])
    if config["cc"]:
        message["Cc"] = ", ".join(config["cc"])
    message["Subject"] = config["subject"]
    message.set_content(_build_email_body(body_results, passed_for_pdf, report_path))

    pdf_bytes = _build_pdf(
        "Surya Sangam - Passed Test Details",
        _flatten_pdf_results(passed_for_pdf),
    )
    message.add_attachment(
        pdf_bytes,
        maintype="application",
        subtype="pdf",
        filename=f"{report_path.stem}_passed_tests.pdf",
    )
    return message


def _parse_test_blocks(report_text):
    """Parse the test-case sections generated by ReportGenerator."""
    blocks = []
    current = None

    for line in report_text.splitlines():
        header = _TEST_HEADER.match(line.strip())
        if header:
            if current:
                blocks.append(current)
            current = {
                "name": header.group(1).strip(),
                "lines": [line.strip()],
                "status": "",
                "area": "General",
            }
            continue

        if current is None:
            continue

        stripped = line.strip()
        current["lines"].append(stripped)
        if stripped in {"PASS", "FAIL", "SKIP"} and not current["status"]:
            current["status"] = stripped
        elif stripped.startswith("Area:"):
            current["area"] = stripped.split(":", 1)[1].strip()

    if current:
        blocks.append(current)

    return [block for block in blocks if block["status"]]


def _split_results(results):
    body_results = []
    passed_for_pdf = []

    for result in results:
        if result["status"] != "PASS" or _is_important(result):
            body_results.append(result)
        else:
            passed_for_pdf.append(result)

    return body_results, passed_for_pdf


def _is_important(result):
    categories = _configured_list(
        "SURYA_REPORT_IMPORTANT_CATEGORIES", DEFAULT_IMPORTANT_CATEGORIES
    )
    keywords = tuple(
        word.lower()
        for word in _configured_list(
            "SURYA_REPORT_IMPORTANT_KEYWORDS", DEFAULT_IMPORTANT_KEYWORDS
        )
    )
    area = result["area"].casefold()
    name = result["name"].casefold()

    return any(area == category.casefold() for category in categories) or any(
        keyword in name for keyword in keywords
    )


def _build_email_body(body_results, passed_for_pdf, report_path):
    failed = sum(result["status"] == "FAIL" for result in body_results)
    skipped = sum(result["status"] == "SKIP" for result in body_results)
    important_passes = sum(
        result["status"] == "PASS" for result in body_results
    )

    lines = [
        "Hello,",
        "",
        "The Surya Sangam automation run is complete.",
        f"Source report: {report_path.name}",
        "",
        "Email summary:",
        f"- Failed tests: {failed}",
        f"- Skipped tests: {skipped}",
        f"- Important passed tests: {important_passes}",
        f"- Other passed tests attached as PDF: {len(passed_for_pdf)}",
        "",
        "Failed, skipped, and important test details:",
    ]

    if not body_results:
        lines.append("No failed, skipped, or important tests were recorded.")
    else:
        for index, result in enumerate(body_results, start=1):
            lines.extend(["", f"{index}. {result['name']}"])
            lines.extend(f"   {line}" for line in result["lines"][1:])

    lines.extend(
        [
            "",
            "The PDF attachment contains passed tests that were not classified as important.",
            "",
            "Regards,",
            "Automation",
        ]
    )
    return "\n".join(lines)


def _flatten_pdf_results(results):
    lines = []
    if not results:
        return ["No non-important passed tests were recorded."]

    for index, result in enumerate(results, start=1):
        lines.append(f"{index}. {result['name']}")
        lines.extend(f"   {line}" for line in result["lines"][1:])
        lines.append("")
    return lines


def _build_pdf(title, lines):
    """Build a simple dependency-free PDF containing wrapped plain text."""
    page_width = 612
    page_height = 792
    left = 45
    top = 755
    line_height = 12
    max_chars = 92
    wrapped = []

    for line in [title, "", *lines]:
        text = str(line)
        if not text:
            wrapped.append("")
            continue
        while len(text) > max_chars:
            split_at = text.rfind(" ", 0, max_chars + 1)
            split_at = split_at if split_at > 0 else max_chars
            wrapped.append(text[:split_at])
            text = text[split_at:].lstrip()
        wrapped.append(text)

    lines_per_page = int((top - 45) / line_height)
    pages = [
        wrapped[index : index + lines_per_page]
        for index in range(0, len(wrapped), lines_per_page)
    ] or [[""]]

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        None,
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    page_object_numbers = []

    for page_lines in pages:
        content_lines = [
            "BT",
            "/F1 9 Tf",
            f"{left} {top} Td",
        ]
        for line in page_lines:
            content_lines.append(f"({_pdf_escape(line)}) Tj")
            content_lines.append(f"0 -{line_height} Td")
        content_lines.append("ET")
        content = "\n".join(content_lines).encode("latin-1", "replace")
        content_object = len(objects) + 1
        objects.append(
            f"<< /Length {len(content)} >>\nstream\n".encode("ascii")
            + content
            + b"\nendstream"
        )
        page_object = len(objects) + 1
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {page_width} {page_height}] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {content_object} 0 R >>".encode(
                "ascii"
            )
        )
        page_object_numbers.append(page_object)

    kids = " ".join(f"{number} 0 R" for number in page_object_numbers)
    objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_object_numbers)} >>".encode(
        "ascii"
    )

    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{number} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_offset = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return bytes(pdf)


def _pdf_escape(value):
    return str(value).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _configured_list(variable, default):
    value = os.getenv(variable)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


def _parse_addresses(value):
    separators_normalized = value.replace(";", ",")
    return [
        address.strip()
        for address in separators_normalized.split(",")
        if address.strip()
    ]


def _validate_report(report_path):
    if not report_path.exists():
        raise FileNotFoundError(f"Report file not found: {report_path}")
    if not report_path.is_file():
        raise FileNotFoundError(f"Report path is not a file: {report_path}")


if __name__ == "__main__":
    try:
        from utils.report_generator import REPORT_FILE
    except ModuleNotFoundError:
        from report_generator import REPORT_FILE

    send_report_email(REPORT_FILE)
